version: '3.7'

services:
  nginx:
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - 8080:80
  api:
    build:
      dockerfile: Dockerfile
      context: ./api
    container_name: api